name: Snowboarding Reminder

on:
  schedule:
    - cron: '0 9 * * 2'  # Runs every Tuesday at 09:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify exact version
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Reminder Script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          PRIMARY_CALENDAR_ID: ${{ secrets.PRIMARY_CALENDAR_ID }}
          SECONDARY_CALENDAR_ID: ${{ secrets.SECONDARY_CALENDAR_ID }}
        run: |
          python Reminder_Script.py
        continue-on-error: false
